### ISSUE TITLE
You must install missing frameworks for .NET 

### ISSUE THREAD

**Issue by CurtisKrokorox** [petfriendamy/UTDR-Music-Randomizer#1]
This looks really cool, but when I try to run UTDRMusicRando.exe, an error message pops up saying I need to install a framework for .NET. There's a lot of options on the website, and I'm not very code savvy. Which version should I download?

**Comment by petfriendamy** [comment]
I thought the popup links you directly to the version you need to download, but I think it's .NET 6.0?

**Comment by CurtisKrokorox** [comment]
No link for me. I tried it with 6.0.0 (x64) and and the error message stopped showing up, but then nothing else happens.

Edit: Figured it out! 6.0.418 x64 is the proper version, apparently.
